### ISSUE TITLE
KeyError: 'portfolio_value'

### ISSUE THREAD

**Issue by GitHubEmploy** [steveman1123/stonkBot#2]
Happens when I run the StonkBot file

**Comment by steveman1123** [comment]
If you have the alpaca keys and are using paper trading, make sure the
isPaper value is set to 1 (true) in the alpacafxns.py file, otherwise it'll
try to use the live trading. If you're trying to use use live trading, make
sure that you're account is active and able to be used (mine took a week or
two if I recall correctly)

GitHubEmploy <notifications@github.com> schrieb am Di., 25. Aug. 2020,
14:54:

**Comment by GitHubEmploy** [comment]
by the way, your bot does not trade alpaca stocks, only shows my portfolio

**Comment by steveman1123** [comment]
It will check to sell during the day, but will only check to buy 10 minutes before market close. So if you have no stocks held, it will not show anything in the tradable stocks part of the output.

Please be more specific about issues you are are encountering, and I urge you to read the comments in the code to get an understanding of how it works.

**Comment by GitHubEmploy** [comment]
Ok, thank you for all your help. I started the bot today at 8:00 am, and it wasn't trading at all the entire day so I stopped it at 11 o clock. So if my understanding is correct, it will only trade in the last 10 minutes? Also, did you try the bot, and what were the estimated daily gains. Thank You.

**Comment by steveman1123** [comment]
No problem! And yes, it will look to buy only in the last 10 minutes, but once you have stocks, it will look to sell at any time of the day. I updated the README with some more information about it too. I have been running it since July and it has returned between 0.75% and 1.5% daily (it has gone down recently due to not running it for a few weeks).
My current setup is to have a raspberry pi setup next to my router and just leave running 24/7

**Comment by GitHubEmploy** [comment]
honestly, that is my current setup too. Thank you for all your help. I will ask here if I have nay more questions.
