### ISSUE TITLE
UnboundLocalError: local variable 'sellDn' referenced before assignment

### ISSUE THREAD

**Issue by GitHubEmploy** [steveman1123/stonkBot#6]
Traceback (most recent call last):
  File "C:/Users/momo/PycharmProjects/SuperAI/stonkBot/stonkBot.py", line 16, in <module>
    main()
  File "C:/Users/momo/PycharmProjects/SuperAI/stonkBot/stonkBot.py", line 13, in main
    algos.mainAlgo() #used to easily switch between the different algos in the algo file
  File "C:\Users\momo\PycharmProjects\SuperAI\stonkBot\alpacaalgos.py", line 85, in mainAlgo
    check2sell(a.getPos(), latestTrades, sellDn, sellUp, sellUpFromClose, sellUpDn)
  File "C:\Users\momo\PycharmProjects\SuperAI\stonkBot\alpacaalgos.py", line 138, in check2sell
    if(curPrice/buyPrice<=sellDn or buyInfo=="Missed jump"):
UnboundLocalError: local variable 'sellDn' referenced before assignment

Happened during last 3 minutes

**Comment by steveman1123** [comment]
Are you on the latest version?

**Comment by GitHubEmploy** [comment]
yes, it was updated yesterday

**Comment by steveman1123** [comment]
Okay, try the latest version. Looks like I did forget to reset the variables

**Comment by GitHubEmploy** [comment]
Actually, I fixed it when I put this at the beginning of the file:

**global sellDn
global sellUp
global sellUpFromClose
global sellUpDn**

The error is because it was referring to it as a local variable, which you cannot refer to outside the function, so these four lines set it as a global variable so it can be referred to inside the function.

**Comment by steveman1123** [comment]
I'm glad it works for you, however, for my use case they are intentionally not global variables namely because of how slow global variable recalling is, but also because at the point where the error occured, those values are set in the previous lines inside the try statement (which appeared to give an exception which is why yours weren't set and so caused the error).

Making the variables global isn't a bad solution in and of itself, but it isn'y my first choice for fixing things
